Trigger workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,22 +19,33 @@ jobs:
       - name: Install dependencies (Linux)
         if: runner.os == 'Linux'
         run: |
-          sudo apt-get update
-          sudo apt-get install -y cmake build-essential
-        retry: 3 # Добавляем retry
-
+          for i in {1..3}; do
+            sudo apt-get update && sudo apt-get install -y cmake build-essential && break || echo "Attempt $i failed"
+            sleep 5 # Wait before retrying
+          done
+          
       - name: Install dependencies (macOS)
         if: runner.os == 'macOS'
         run: |
-          brew install cmake
-        retry: 3
-
+          for i in {1..3}; do
+            brew install cmake && break || echo "Attempt $i failed"
+            sleep 5 # Wait before retrying
+          done
+          
       - name: Install dependencies (Windows)
         if: runner.os == 'Windows'
-        run: |
-          choco install cmake ninja -y --no-progress --ignore-checksums || scoop install cmake #Пытаемся установить cmake через scoop если choco не сработал
         shell: powershell
-        retry: 3
+        run: |
+          $retries = 3
+          for ($i = 1; $i -le $retries; $i++) {
+            try {
+              choco install cmake ninja -y --no-progress --ignore-checksums -Force
+              break # Exit the loop if successful
+            } catch {
+              Write-Host "Attempt $($i) failed: $($_.Exception.Message)"
+              Start-Sleep -Seconds 5 # Wait before retrying
+            }
+          }
 
       - name: Create build directory
         run: mkdir -p build
